# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.
name: Pytest
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v7.1.2
        with:
          # The version of Python to set UV_PYTHON to
          python-version: 3.12.3
          # Use uv venv to activate a venv ready to be used by later steps.
          activate-environment: true
          # Glob pattern to match files relative to the repository root to control the cache.
          cache-dependency-glob: "**/pyproject.toml"

      # And finally run tests. I'm using pytest and all my pytest config is in my `pyproject.toml`
      # so this line is super-simple. But it could be as complex as you need.
      - run: pytest
